### PR TITLE
added pip package data

### PR DESCRIPTION
**Pull request by AND2797**
I have bundled all the required files in `package_data` required for uploading the package to PyPI. Suggest testing on PyPI test servers first.

### CODE REVIEW

**Review by ideasman42 — CHANGES_REQUESTED** [review]
This duplicates the entire package contents which isn't necessary.

Please only include files needed to create the package.

**Comment by ideasman42** [comment]
This is still adding a duplicate `readme.rst`, no files should be duplicated as result of supporting pip.

**Comment by AND2797** [comment]
> This is still adding a duplicate `readme.rst`, no files should be duplicated as result of supporting pip.


Got it, I will make a revision and push it for review.

**Comment by AND2797** [comment]
I have pushed a new commit which only includes the required files.

**Comment by ideasman42** [comment]
This pr still includes duplicate files & binary files.

**Comment by ideasman42** [comment]
There are too many changes in this PR without any explanation.

Please submit smaller PR's that note what they do.

For example in `setup.py`

`py_modules=['poly_point_isect'],` is replaced by `packages=["poly_point_isect"],` - what does this fix?

----

I tested `python setup.py install` and it worked as expected.

Could you submit a new PR with only changes to include `package_data`, any other changes make separately with an explanation of what they do.

**Pull request closed without merging**
